function yalmip_install()

    PathToAdd = {  '.',...
        'extras', ...
        'solvers', ...
        'modules', ...
        'modules/parametric', ...
        'modules/moment', ...
        'modules/global', ...
        'modules/robust', ...
        'modules/sos', ...
        'operators'};

    for i = 1:length(PathToAdd)
        yalmip_path = fullfile(pwd, PathToAdd{i});
        addpath(yalmip_path)
        fprintf('Add and save path %s to MATLAB search path.\n', yalmip_path);
    end

    savepath;
    yalmipdemo

end